#!/bin/bash
pushd .
cd DotNetPlug.Native
make ENGINE=csgo clean && make ENGINE=csgo
popd
xbuild DotNetPlug.Managed/DotNetPlug.Managed.csproj /p:Configuration=Release 
xbuild DotNetPlug.Managed.Sample/DotNetPlug.Managed.Sample.csproj /p:Configuration=Release 
