// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.0.0.19191
//    <NameSpace>MonoPlug</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLasyLoading>False</EnableLasyLoading><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><DisableDebug>True</DisableDebug><CustomUsings></CustomUsings>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MonoPlug
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

    /// <summary>
    /// Type for config file
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlRootAttribute("config", Namespace = "", IsNullable = false)]
    public partial class TConfig
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private TMySQL mysqlField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<TPlugin> pluginField;

        /// <summary>
        /// .ctor class constructor
        /// </summary>
        public TConfig()
        {
            this.pluginField = new List<TPlugin>();
            this.mysqlField = new TMySQL();
        }
        /// <summary>
        /// mysql
        /// </summary>
        public TMySQL mysql
        {
            get
            {
                return this.mysqlField;
            }
            set
            {
                this.mysqlField = value;
            }
        }

        /// <summary>
        /// plugin
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("plugin")]
        public List<TPlugin> plugin
        {
            get
            {
                return this.pluginField;
            }
            set
            {
                this.pluginField = value;
            }
        }
    }

    /// <summary>
    /// TMySQL
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class TMySQL
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string hostField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private int portField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string userField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string passField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string baseField;

        /// <summary>
        /// TMySQL
        /// </summary>
        public TMySQL()
        {
            this.portField = 3306;
        }

        /// <summary>
        /// host
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(3306)]
        public int port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pass
        {
            get
            {
                return this.passField;
            }
            set
            {
                this.passField = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
    }

    /// <summary>
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class TPlugin
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nameField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool loadedField;

        /// <summary>
        /// 
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool loaded
        {
            get
            {
                return this.loadedField;
            }
            set
            {
                this.loadedField = value;
            }
        }
    }
}
